name: Setup Velociraptor
description: Install Velociraptor scripts manager
author: JurassiScripts
branding:
  icon: terminal
  color: blue
inputs:
  checkout:
    description: Whether to checkout repository first
    default: true
    required: false
  deno-version:
    description: Deno version to use
    default: 1.x
    required: false
  velociraptor-version:
    description: Velociraptor version to use
    default: latest
    required: false
  velociraptor-alias:
    description: Velociraptor alias name
    default: vr
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      if: ${{ inputs.checkout }}
    - uses: denoland/setup-deno@v1
      if: ${{ inputs.deno-version }}
      with: 
        deno-version: ${{ inputs.deno-version }}
    - shell: bash
      run: |
        case "${{ inputs.velociraptor-version }}" in
          "latest") ;; "") ;;
          *) VERSION=@${{ inputs.velociraptor-version }} ;;
        esac
        deno install --allow-all --name ${{ inputs.velociraptor-alias }} https://deno.land/x/velociraptor$VERSION/cli.ts
        echo "/home/runner/.deno/bin" >> $GITHUB_PATH
    - shell: bash
      if: ${{ contains(runner.os, 'macos') }}
      run: |
        echo "/Users/runner/.deno/bin" >> $GITHUB_PATH
    - shell: powershell
      if: ${{ contains(runner.os, 'windows') }}
      run: |
        echo "C:\Users\runneradmin\.deno\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append