name: Setup Velociraptor
description: Install Velociraptor scripts manager
author: JurassiScripts
branding:
  icon: terminal
  color: blue
inputs:
  velociraptor-version:
    description: Version to use
    default: latest
    required: false
  velociraptor-alias:
    description: Alias name
    default: vr
    required: false
runs:
  using: composite
  steps:
    - run: |
        case "${{ inputs.velociraptor-version }}" in
          "latest") ;; "") ;;
          *) VERSION=@${{ inputs.velociraptor-version }} ;;
        esac
        deno install --allow-all --name ${{ inputs.velociraptor-alias }} https://deno.land/x/velociraptor$VERSION/cli.ts
        echo "/home/runner/.deno/bin" >> $GITHUB_PATH
      shell: bash
    - run: |
        echo "C:\Users\runneradmin\.deno\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      if: ${{ runner.os == "Windows" }}